SuppliersAndProducts/SuppliersAndProduct.MVC/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SuppliersAndProduct.MVC.Helper;
using SuppliersAndProducts.Models.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace SuppliersAndProduct.MVC.Controllers
{
    public class ProductsController : Controller
    {
        HelperAPI api = new HelperAPI();
        public async Task<IActionResult> Index()
        {
            List<Product> products = new List<Product>();
            HttpClient client = api.Initial();
            HttpResponseMessage res = await client.GetAsync("api/products/GetProducts");
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                products = JsonConvert.DeserializeObject<List<Product>>(result);
            }
            return View(products);
        }
        public async Task<IActionResult> Delete(int id)
        {
            
            HttpClient client = api.Initial();
            HttpResponseMessage res = await client.DeleteAsync($"api/products/Delete/{id}");
            return RedirectToAction("Index");
        }

    }
}

SuppliersAndProducts/SuppliersAndProduct.MVC/Controllers/SuppliersController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SuppliersAndProduct.MVC.Helper;
using SuppliersAndProducts.Models.Classes;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Net.Http;

using System.Text;
using System.Threading.Tasks;

namespace SuppliersAndProduct.MVC.Controllers
{
    public class SuppliersController : Controller
    {

        HelperAPI api = new HelperAPI();
        public async Task<IActionResult> Index()
        {
            List<Supplier> suppliers = new List<Supplier>();
            HttpClient client = api.Initial();
            HttpResponseMessage res = await client.GetAsync("api/Suppliers/GetSuppliers");
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                suppliers = JsonConvert.DeserializeObject<List<Supplier>>(result);
            }
           
            
            return View(suppliers);
        }

        public async Task<IActionResult> Details(int id)
        {
            var supplier = new Supplier();
            HttpClient client = api.Initial();
            HttpResponseMessage res = await client.GetAsync($"api/suppliers/GetSupplierByID/{id}");
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                supplier = JsonConvert.DeserializeObject<Supplier>(result);

            }
            return View(supplier);
        }
        public async Task<IActionResult> ProductBySupplierID(int id)
        {

            HttpClient client = api.Initial();
            HttpResponseMessage res = await client.GetAsync($"api/suppliers/GetProductBySupplier/{id}");
            var result = res.Content.ReadAsStringAsync().Result;
            var products = JsonConvert.DeserializeObject<List<Product>>(result);
            return View(products);

        }
        public async Task<IActionResult> Delete(int id)
        {
            HttpClient client = api.Initial();
            HttpResponseMessage res = await client.DeleteAsync($"api/suppliers/Delete/{id}");
            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {

            return View();
        }
       
        [HttpPost]
        public IActionResult Create( Supplier supplier) 
        {
            HttpClient client = api.Initial();
            var postTask =  client.PostAsJsonAsync($"api/suppliers/add", supplier);
            postTask.Wait();
            var result =  postTask.Result;
            if (result.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return View();
        }

        public ActionResult Edit()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Edit(Supplier supplier)
        {
            HttpClient client = api.Initial();
            var postTask = client.PutAsJsonAsync($"api/suppliers/Update", supplier);
            postTask.Wait();
            var result = postTask.Result;
            if (result.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        
        public IActionResult UpdateSupplier1()
        {
            return null;
        }

    }
}

SuppliersAndProducts/SuppliersAndProduct.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> SuppliersAndProducts </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow mb-3  bg-primary">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Suppliers" asp-action="Index">Suppliers&Product</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Suppliers" asp-action="Index">Suppliers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SuppliersAndProduct.MVC 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>